name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  merge_group:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  codecov-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Extract Node.js version from .nvmrc
      - name: Get Node.js version from .nvmrc
        id: node_version
        run: |
          NODE_VERSION=$(cat .nvmrc)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Install
        run: npm run build

      - name: Test
        run: npm run test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: coverage
          path: coverage/
          retention-days: 5

      - name: Docs
        run: npm run docs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # e2e:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     # Extract Node.js version from .nvmrc
  #     - name: Get Node.js version from .nvmrc
  #       id: node_version
  #       run: |
  #         NODE_VERSION=$(cat .nvmrc)
  #         echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
  #     - uses: actions/setup-node@v4
  #       with:
  #         # we need 'fetch' for this test, which is only in 18
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Install
  #       run: npm ci

  #     - name: Build
  #       run: npm run build

  #     - name: SDK e2e tests
  #       run: npm run e2e
